version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: online_store
    ports:
      - "5433:5432"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/db_init.sql
      - ./data:/var/lib/postgresql/data
    networks:
      - postgres-network
    restart: always

networks:
  postgres-network:
    driver: bridge